Repository lion-packages/request, pull requests merged in 2024-12, with the labels that each got.

#12 Support with PHP 8.4
  .idea/.gitignore
  .idea/modules.xml
  .idea/php.xml
  .idea/phpunit.xml
  .idea/request.iml
  .idea/vcs.xml
  Dockerfile
  composer.json
  composer.lock
Labels: continuous integration, dependencies

#14 Github Actions Integration
  .github/workflows/php.yml
  composer.json
  composer.lock
  src/LionRequest/Status.php
Labels: continuous integration, dependencies

#15 Support and Maintenance
  Dockerfile
  test.sh
Labels: continuous integration

#16 Updated GitHub Actions configuration
  .github/workflows/php.yml
Labels: continuous integration

#17 Added PHPStan support and validation
  .github/workflows/php.yml
  src/LionRequest/Request.php
Labels: enhancement
