Repository lion-packages/request, pull requests merged in 2025-03, with the labels that each got.

#21 update phpunit v12
  Dockerfile
  composer.json
  phpunit.xml
Labels: dependencies

#22 The infection library is installed
  composer.json
  infection.json5
  src/LionRequest/Request.php
  src/LionRequest/Response.php
  tests/RequestTest.php
  tests/ResponseTest.php
Labels: dependencies, tests

#23 Updated Github Actions settings
  .github/workflows/php.yml
Labels: continuous integration

#24 The infection is added to Github Actions
  .github/workflows/php.yml
Labels: continuous integration

#25 Added dependency-review in Github Actions
  .github/workflows/php.yml
  infection.json
Labels: continuous integration

#26 Added dependabot
  .github/workflows/dependabot.yml
Labels: continuous integration

#27 Dependabot is relocated
  .github/dependabot.yml
Labels: continuous integration

#29 PHPLint is integrated
  .github/workflows/php.yml
  .gitignore
  composer.json
Labels: continuous integration, dependencies

#30 Update README.md
  .github/README.md
Labels: documentation
